#pragma once
#include <QtCore>

constexpr quint32 FUNC_Alpha_ADDF = 0x80;         // Add F_floating
constexpr quint32 FUNC_Alpha_SUBF = 0x81;         // Subtract F_floating
constexpr quint32 FUNC_Alpha_MULF = 0x82;         // Multiply F_floating
constexpr quint32 FUNC_Alpha_DIVF = 0x83;         // Divide F_floating
constexpr quint32 FUNC_VAX_ADDF_IC = 0x000;       //   ADDF
constexpr quint32 FUNC_VAX_SUBF_IC = 0x001;       //   SUBF
constexpr quint32 FUNC_VAX_MULF_IC = 0x002;       //   MULF
constexpr quint32 FUNC_VAX_DIVF_IC = 0x003;       //   DIVF
constexpr quint32 FUNC_VAX_CVTDG_IC = 0x01E;      //   CVTDG
constexpr quint32 FUNC_VAX_ADDG_IC = 0x020;       //   ADDG
constexpr quint32 FUNC_VAX_SUBG_IC = 0x021;       //   SUBG
constexpr quint32 FUNC_VAX_MULG_IC = 0x022;       //   MULG
constexpr quint32 FUNC_VAX_DIVG_IC = 0x023;       //   DIVG
constexpr quint32 FUNC_VAX_CVTGF_IC = 0x02C;      //   CVTGF
constexpr quint32 FUNC_VAX_CVTGD_IC = 0x02D;      //   CVTGD
constexpr quint32 FUNC_VAX_CVTGQ_IC = 0x02F;      //   CVTGQ
constexpr quint32 FUNC_VAX_CVTQF_IC = 0x03C;      //   CVTQF
constexpr quint32 FUNC_VAX_CVTQG_IC = 0x03E;      //   CVTQG
constexpr quint32 FUNC_Alpha_CVTDG = 0x09E;      //   CVTDG
constexpr quint32 FUNC_Alpha_ADDG = 0x0A0;       // Add G_floating
constexpr quint32 FUNC_Alpha_SUBG = 0x0A1;        // Subtract G_floating
constexpr quint32 FUNC_Alpha_MULG = 0x0A2;       // Multiply G_floating
constexpr quint32 FUNC_Alpha_DIVG = 0x0A3;       // Divide G_floating
constexpr quint32 FUNC_Alpha_CMPGEQ = 0xA05;     // Compare G_floating Equal
constexpr quint32 FUNC_Alpha_CMPGLT = 0x0A6;     // Compare G_floating Less Than
constexpr quint32 FUNC_Alpha_CMPGLE = 0x0A7;     // Compare G_floating Less Than or Equal
constexpr quint32 FUNC_VAX_DIVF = 0x083;         //   DIVF
constexpr quint32 FUNC_Alpha_CVTGF = 0x0AC;      //   CVTGF
constexpr quint32 FUNC_Common_CVTGD = 0x0AD; //   CVTGD
constexpr quint32 FUNC_Common_CVTQF = 0x0BC; //   CVTQF
constexpr quint32 FUNC_Common_CVTQG = 0x0BE; //   CVTQG
constexpr quint32 FUNC_VAX_CMPGLE = 0x0A7;       //   CMPGLE
constexpr quint32 FUNC_VAX_ADDF_UC = 0x100;       //   ADDF
constexpr quint32 FUNC_VAX_SUBF_UC = 0x101;       //   SUBF
constexpr quint32 FUNC_VAX_MULF_UC = 0x102;       //   MULF
constexpr quint32 FUNC_VAX_DIVF_UC = 0x103;       //   DIVF
constexpr quint32 FUNC_VAX_CVTDG_UC = 0x11E;      //   CVTDG
constexpr quint32 FUNC_VAX_ADDG_UC = 0x120;       //   ADDG
constexpr quint32 FUNC_VAX_SUBG_UC = 0x121;       //   SUBG
constexpr quint32 FUNC_VAX_MULG_UC = 0x122;       //   MULG
constexpr quint32 FUNC_VAX_DIVG_UC = 0x123;       //   DIVG
constexpr quint32 FUNC_VAX_CVTGF_UC = 0x12C;      //   CVTGF
constexpr quint32 FUNC_VAX_CVTGD_UC = 0x12D;      //   CVTGD
constexpr quint32 FUNC_VAX_CVTGQ_NC = 0x12F;      //   CVTGQ
constexpr quint32 FUNC_VAX_ADDF_U = 0x180;        //   ADDF
constexpr quint32 FUNC_VAX_SUBF_U = 0x181;        //   SUBF
constexpr quint32 FUNC_VAX_MULF_U = 0x182;        //   MULF
constexpr quint32 FUNC_VAX_DIVF_U = 0x183;        //   DIVF
constexpr quint32 FUNC_VAX_CVTDG_U = 0x19E;       //   CVTDG
constexpr quint32 FUNC_VAX_ADDG_U = 0x1A0;        //   ADDG
constexpr quint32 FUNC_VAX_SUBG_U = 0x1A1;        //   SUBG
constexpr quint32 FUNC_VAX_MULG_U = 0x1A2;        //   MULG
constexpr quint32 FUNC_VAX_DIVG_U = 0x1A3;        //   DIVG
constexpr quint32 FUNC_VAX_CVTGF_U = 0x1AC;       //   CVTGF
constexpr quint32 FUNC_VAX_CVTGD_U = 0x1AD;       //   CVTGD
constexpr quint32 FUNC_VAX_CVTGQ_V = 0x1AF;       //   CVTGQ
constexpr quint32 FUNC_VAX_ADDF_SC = 0x400;       //   ADDF
constexpr quint32 FUNC_VAX_SUBF_SC = 0x401;       //   SUBF
constexpr quint32 FUNC_VAX_MULF_SC = 0x402;       //   MULF
constexpr quint32 FUNC_VAX_DIVF_SC = 0x403;       //   DIVF
constexpr quint32 FUNC_VAX_CVTDG_SC = 0x41E;      //   CVTDG
constexpr quint32 FUNC_VAX_ADDG_SC = 0x420;       //   ADDG
constexpr quint32 FUNC_VAX_SUBG_SC = 0x421;       //   SUBG
constexpr quint32 FUNC_VAX_MULG_SC = 0x422;       //   MULG
constexpr quint32 FUNC_VAX_DIVG_SC = 0x423;       //   DIVG
constexpr quint32 FUNC_VAX_CVTGF_SC = 0x42C;      //   CVTGF
constexpr quint32 FUNC_VAX_CVTGD_SC = 0x42D;      //   CVTGD
constexpr quint32 FUNC_VAX_CVTGQ_SC = 0x42F;      //   CVTGQ
constexpr quint32 FUNC_VAX_ADDF_IS = 0x480;       //   ADDF
constexpr quint32 FUNC_VAX_SUBF_IS = 0x481;       //   SUBF
constexpr quint32 FUNC_VAX_MULF_IS = 0x482;       //   MULF
constexpr quint32 FUNC_VAX_DIVF_IS = 0x483;       //   DIVF
constexpr quint32 FUNC_VAX_CVTDG_IS = 0x49E;      //   CVTDG
constexpr quint32 FUNC_VAX_ADDG_IS = 0x4A0;       //   ADDG
constexpr quint32 FUNC_VAX_SUBG_IS = 0x4A1;       //   SUBG
constexpr quint32 FUNC_VAX_MULG_IS = 0x4A2;       //   MULG
constexpr quint32 FUNC_VAX_DIVG_IS = 0x4A3;       //   DIVG
constexpr quint32 FUNC_VAX_CMPGEQ_IC = 0x4A5;     //   CMPGEQ
constexpr quint32 FUNC_VAX_CMPGLT_IC = 0x4A6;     //   CMPGLT
constexpr quint32 FUNC_VAX_CMPGLE_IC = 0x4A7;     //   CMPGLE
constexpr quint32 FUNC_VAX_CVTGF_IS = 0x4AC;      //   CVTGF
constexpr quint32 FUNC_VAX_CVTGD_IS = 0x4AD;      //   CVTGD
constexpr quint32 FUNC_VAX_CVTGQ_IS = 0x4AF;      //   CVTGQ
constexpr quint32 FUNC_VAX_ADDF_SUC = 0x500;      //   ADDF
constexpr quint32 FUNC_VAX_SUBF_SUC = 0x501;      //   SUBF
constexpr quint32 FUNC_VAX_MULF_SUC = 0x502;      //   MULF
constexpr quint32 FUNC_VAX_DIVF_SUC = 0x503;      //   DIVF
constexpr quint32 FUNC_VAX_CVTDG_SUC = 0x51E;     //   CVTDG
constexpr quint32 FUNC_VAX_ADDG_SUC = 0x520;      //   ADDG
constexpr quint32 FUNC_VAX_SUBG_SUC = 0x521;      //   SUBG
constexpr quint32 FUNC_VAX_MULG_SUC = 0x522;      //   MULG
constexpr quint32 FUNC_VAX_DIVG_SUC = 0x523;      //   DIVG
constexpr quint32 FUNC_VAX_CVTGF_SUC = 0x52C;     //   CVTGF
constexpr quint32 FUNC_VAX_CVTGD_SUC = 0x52D;     //   CVTGD
constexpr quint32 FUNC_VAX_CVTGQ_SVC = 0x52F;     //   CVTGQ
constexpr quint32 FUNC_VAX_ADDF_SU = 0x580;       //   ADDF
constexpr quint32 FUNC_VAX_SUBF_SU = 0x581;       //   SUBF
constexpr quint32 FUNC_VAX_MULF_SU = 0x582;       //   MULF
constexpr quint32 FUNC_VAX_DIVF_SU = 0x583;       //   DIVF
constexpr quint32 FUNC_VAX_CVTDG_SU = 0x59E;      //   CVTDG
constexpr quint32 FUNC_VAX_ADDG_SU = 0x5A0;       //   ADDG
constexpr quint32 FUNC_VAX_SUBG_SU = 0x5A1;       //   SUBG
constexpr quint32 FUNC_VAX_MULG_SU = 0x5A2;       //   MULG
constexpr quint32 FUNC_VAX_DIVG_SU = 0x5A3;       //   DIVG
constexpr quint32 FUNC_VAX_CVTGF_SU = 0x5AC;      //   CVTGF
constexpr quint32 FUNC_VAX_CVTGD_SU = 0x5AD;      //   CVTGD
constexpr quint32 FUNC_Common_Vax_CVTGQ = 0x0AF; //   CVTGQ
constexpr quint32 FUNC_VAX_CVTGQ_SV = 0x5AF;      //   CVTGQ
constexpr quint32 FUNC_VAX_CVTBQ_C = 0x02F;       //   CVTBQ
