
#include <QtCore>
#pragma once
constexpr quint32 FUNC_Alpha_ADDL= 0x00;    //   ADDL
constexpr quint32 FUNC_Alpha_ADDL= 0x40;   //   ADDL
constexpr quint32 FUNC_Alpha_ADDQ= 0x20;   //   ADDQ
constexpr quint32 FUNC_Alpha_ADDQ= 0x60;   //   ADDQ
constexpr quint32 FUNC_Alpha_CMPBGE= 0x0F; //   CMPBGE
constexpr quint32 FUNC_Alpha_CMPEQ= 0x2D;  //   CMPEQ
constexpr quint32 FUNC_Alpha_CMPLE= 0x6D;  //   CMPLE
constexpr quint32 FUNC_Alpha_CMPLT= 0x4D;  //   CMPLT
constexpr quint32 FUNC_Alpha_CMPNE = 0x2E;       // Compare Equal
constexpr quint32 FUNC_Alpha_CMPULE_G = 0x3F;    // unsigned -  (quadword)
constexpr quint32 FUNC_Alpha_CMPULE_L = 0x1F;    // unsigned -  (longword)
constexpr quint32 FUNC_Alpha_CMPULE = 0x3D; //   CMPULE
constexpr quint32 FUNC_Alpha_CMPULT_G = 0x3D; // unsigned <  (quadword)
constexpr quint32 FUNC_Alpha_CMPULT_L = 0x1D; // unsigned <  (longword)
constexpr quint32 FUNC_Alpha_CMPULT= 0x1D; //   CMPULT
constexpr quint32 FUNC_Alpha_S4ADDL= 0x2;  //   S4ADDL
constexpr quint32 FUNC_Alpha_S4ADDQ= 0x22; //   S4ADDQ
constexpr quint32 FUNC_Alpha_S4SUBL= 0x0B; //   S4SUBL
constexpr quint32 FUNC_Alpha_S4SUBQ= 0x2B; //   S4SUBQ
constexpr quint32 FUNC_Alpha_S8ADDL= 0x12; //   S8ADDL
constexpr quint32 FUNC_Alpha_S8ADDQ= 0x32; //   S8ADDQ
constexpr quint32 FUNC_Alpha_S8SUBL= 0x1B; //   S8SUBL
constexpr quint32 FUNC_Alpha_S8SUBQ= 0x3B; //   S8SUBQ

constexpr quint32 FUNC_Alpha_SUBL_V = 0x49;  //   SUBL
constexpr quint32 FUNC_Alpha_SUBL= 0x9;    //   SUBL
constexpr quint32 FUNC_Alpha_SUBQ_V = 0x69;  //   SUBQ
constexpr quint32 FUNC_Alpha_SUBQ= 0x29;   //   SUBQ
constexpr quint32 FUNC_S4ADDL = 0x02;        // Scaled Add Longword by 4
constexpr quint32 FUNC_S4ADDLV = 0x42;       // Scaled Add Longword by 4 with overflow
constexpr quint32 FUNC_S4ADDQ = 0x22;        // Scaled Add Quadword by 4
constexpr quint32 FUNC_S4ADDQV = 0x62;       // Scaled Add Quadword by 4 with overflow
constexpr quint32 FUNC_S4SUBL = 0x0B;        // Scaled Subtract Longword by 4
constexpr quint32 FUNC_S4SUBLV = 0x4B;       // Scaled Subtract Longword by 4 with overflow
constexpr quint32 FUNC_S4SUBQ = 0x2B;        // Scaled Subtract Quadword by 4
constexpr quint32 FUNC_S4SUBQV = 0x6B;       // Scaled Subtract Quadword by 4 with overflow
constexpr quint32 FUNC_S8ADDL = 0x12;        // Scaled Add Longword by 8
constexpr quint32 FUNC_S8ADDLV = 0x52;       // Scaled Add Longword by 8 with overflow
constexpr quint32 FUNC_S8ADDQ = 0x32;        // Scaled Add Quadword by 8
constexpr quint32 FUNC_S8ADDQV = 0x72;       // Scaled Add Quadword by 8 with overflow
constexpr quint32 FUNC_S8SUBL = 0x1B;        // Scaled Subtract Longword by 8
constexpr quint32 FUNC_S8SUBLV = 0x5B;       // Scaled Subtract Longword by 8 with overflow
constexpr quint32 FUNC_S8SUBQ = 0x3B;        // Scaled Subtract Quadword by 8
constexpr quint32 FUNC_S8SUBQV = 0x7B;       // Scaled Subtract Quadword by 8 with overflow
constexpr quint32 FUNC_SUBL = 0x09;          // Subtract Longword
constexpr quint32 FUNC_SUBLV = 0x49;         // Subtract Longword with overflow
constexpr quint32 FUNC_SUBQ = 0x29;          // Subtract Quadword
constexpr quint32 FUNC_SUBQV = 0x69;         // Subtract Quadword with overflow
