#pragma once
#include <QtCore>

enum class enumInstructionPerformance {
	BRANCH_INSTRUCTIONS,
	BRANCHES_TAKEN,
	BRANCHES_NOT_TAKEN,
	BRANCHNES_MISPREDICTIONS,
    HW_MFPR_COUNT,
    HW_MTPR_COUNT,
	HW_LD_COUNT,
	HW_ST_COUNT,
	HW_REI_COUNT,
	HARDWARE_INSTRUCTIONS,
	HARDWARE_INSTRUCTION_CYLES
};
