#pragma once
enum class MemoryFaultType
{
    NONE,
    ACCESS_VIOLATION,
    ALIGNMENT_FAULT,
    DOUBLE_FAULT,
    FAULT_ON_READ,
    EXECUTION_FAULT,
    FAULT_ON_WRITE,
    GENERAL_PROTECTION_FAULT,
    INSTRUCTION_ACCESS_FAULT,
    INVALID_ADDRESS,
    MACHINE_CHECK,
    MMIO_ERROR,
    PAGE_FAULT,
    PROTECTION_VIOLATION,
    PRIVILEGE_VIOLATION,
    READ_ERROR,
    TRANSLATION_NOT_VALID,
    WRITE_ERROR
};
