#pragma once
enum class ExceptionCause
{
    EXCEPTION_CAUSE_UNKNOWN,
    EXCEPTION_CAUSE_AST,
    EXCEPTION_CAUSE_INTERRUPT,
    EXCEPTION_CAUSE_MACHINE_CHECK,
    EXCEPTION_CAUSE_ALIGNMENT,
    EXCEPTION_CAUSE_ILLEGAL_INSTR

};