#pragma once
enum class FPTrapType
{
    FP_ARITHMETIC_TRAP,
    FP_DISABLED,
    FP_DIVISION_BY_ZERO,
    FP_INEXACT,
    FP_INVALID_OPERATION,
    FP_OVERFLOW,
    FP_TRAP_UNKNOWN,
    FP_UNDERFLOW,
    FP_EXCEPTION,
    FP_MACHINE_CHECK, 
    FP_UNALIGNED_ACCESS,
    PAL_FAULT,
    UNKNOWN
};